Tiger_CTF/Tiger_CTF/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from home import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from challenges import urls
from naming import urls as naming_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', auth_views.login, {'template_name':'userpages/login.html'}, name='login'),
    url(r'^logout$', auth_views.logout,{'template_name':'userpages/logout.html'}, name='logout'),
    url(r'^home$', views.home, name='home'),
    url(r'^user/', include('userpages.urls', namespace='userpages')),
    url(r'^challenges/', include(urls, namespace='challenges')),
    url(r'^naming/', include(naming_urls, namespace='naming')),
]
#Have django serve stati files and media in debug mode
#the apache server will take care of this when the server is
#deployed
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tiger_CTF/challenges/urls.py
from django.conf.urls import include, url
import views

urlpatterns = [
        url(r'^$', views.challenges, name='challenges'), 
        url(r'^(?P<challenge_number>[0-9]+)$', views.challenge, name='challenge'),
        ]

Tiger_CTF/naming/urls.py
from django.conf.urls import include, url
from .views import naming, vote, score

urlpatterns = [
        url(r'^$', naming, name = 'naming'),
        url(r'^vote/([0-9]+)$', vote, name='vote'),
        url(r'^score/([0-9]+)$', vote, name='score'),
        ]

Tiger_CTF/home/models.py
from django.db import models

# Create your models here.

Tiger_CTF/home/views.py
from django.http import Http404
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    return render(request,'home/home.html')




# Create your views here.

Tiger_CTF/home/templates/base-navbar.html
{% extends 'base.html' %}
{% block navbar %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target="#CTFNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href={% url 'naming:naming' %}>Naming</a>
        </div>
        <div class="collapse navbar-collapse" id="CTFNavbar">
            <ul class="nav navbar-nav">
                {% block nav_contents %}
                <li class="active"><a href={% url 'home' %}>Home</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="{% url 'challenges:challenges' %}">Challenges</a></li>
                {% endblock %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href={% url 'logout' %}><span class="glyphicon glyphicon-log-out"</span>
                    Logout</a></li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

Tiger_CTF/home/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}CFLT Naming{% endblock %}
    </title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'home/base.css' %}">
    <link rel="stylesheet" href="{% static 'chartist/dist/chartist.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.js' %}"></script>
    <script src="{% static 'chartist/dist/chartist.min.js' %}"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block navbar %}
    {% endblock %}
    <div class="container-fluid container_bg">

        {% block page-header %}
        <div class="page-header">
            <div class='row'>
                <div class='hidden-xs col-sm-4'>
                    <img src={% static 'home/insigniastuff.png' %} height=90 width=87 class='img-responsive '>
                </div>
                <div class='col-sm-4'>
                    {% block page_title %}
                    <h1>CFLT Naming</h1>
                    {% endblock %}
                </div>
                <div class='hidden-xs col-sm-4'>
                    <img src={% static 'home/usairforce.png' %} height=105 width=100 class='img-responsive pull-right'>
                </div>
            </div>
        </div>
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>