Tiger_CTF/Tiger_CTF/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from home import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from challenges import urls
from naming import urls as naming_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', auth_views.login, {'template_name':'userpages/login.html'}, name='login'),
    url(r'^logout$', auth_views.logout,{'template_name':'userpages/logout.html'}, name='logout'),
    url(r'^home$', views.home, name='home'),
    url(r'^user/', include('userpages.urls', namespace='userpages')),
    url(r'^challenges/', include(urls, namespace='challenges')),
    url(r'^naming/', include(naming_urls, namespace='naming')),
]
#Have django serve stati files and media in debug mode
#the apache server will take care of this when the server is
#deployed
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tiger_CTF/naming/urls.py
from django.conf.urls import include, url
from .views import naming, vote, score

urlpatterns = [
        url(r'^$', naming, name = 'naming'),
        url(r'^vote/([0-9]+)$', vote, name='vote'),
        url(r'^score/([0-9]+)$', vote, name='score'),
        ]

Tiger_CTF/userpages/urls.py
from django.conf.urls import include, url
from userpages.views import registration_view

urlpatterns = [
    url(r'^register$', registration_view, name='register'),
] 

Tiger_CTF/userpages/models.py
from django.db import models

# Create your models here.

Tiger_CTF/userpages/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class Register(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(Register, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

Tiger_CTF/userpages/views.py
from django.shortcuts import render
from django.http import Http404
from django.shortcuts import render,redirect
from forms import Register

def registration_view(request):
    if request.method == "POST":
        form = Register(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = Register()
    context = {
            'form': form,
            'title':'Registration Page',
            }
    return render(request,'userpages/register.html', context)


# Create your views here.

Tiger_CTF/userpages/templates/userpages/login.html
{% extends 'userpages/userpages-base.html' %}
{% block userpages-content %}
    <script type="text/javascript" >
        $(document).ready(function(){
            $("#id_username").attr('placeholder', '{{form.username.label}}');
            $("#id_password").attr('placeholder', '{{form.password.label}}');
        });
    </script>
    <legend>Please Sign In</legend>
    {% if form.errors %}
            <div class="alert alert-danger">
                Your username and password didn't match. Please try again.
            </div>
    {% endif %}
    <form role="form" action="{% url 'django.contrib.auth.views.login' %}"
        method="post" class ="forminput">
        {% csrf_token %}
        <div class="input-group input-group-sm">
            <span class="glyphicon glyphicon-user input-group-addon"></span>
            {{ form.username }}
        </div>
        <div class="input-group input-group-sm">
            <span class="glyphicon glyphicon-lock input-group-addon"></span>
            {{ form.password }}
        </div>
        <div class="input-group input-group-sm">
        </div>
            <button type="submit" name="submit" class="btn btn-default">Sign in</button>
    </form>
    <a href={% url 'userpages:register' %}>Register<a>
{% endblock %}

Tiger_CTF/userpages/templates/userpages/logout.html
{% extends 'userpages/userpages-base.html' %}
{% block userpages-content %}
    <legend>Thank you for playing, Please come again!</legend>
    <a href={% url 'login' %} class="btn btn-default btn-block" role="button">Login</a>
{% endblock %}

Tiger_CTF/userpages/templates/userpages/register.html
{% extends 'userpages/userpages-base.html' %}
{% block userpages-content %}
    <script type="text/javascript" >
        $(document).ready(function(){
            $("#id_username").attr('placeholder', '{{form.username.label}}');
            $("#id_email").attr('placeholder', '{{form.email.label}}');
            $("#id_password1").attr('placeholder', '{{form.password1.label}}');
            $("#id_password2").attr('placeholder', '{{form.password2.label}}');
        });
    </script>

    <legend>Please Enter Your Information</legend>
    <form role="form" userpages_urlsaction="Login" method="post" class ="forminput">
        {% csrf_token %}
        <div class="input-group input-group-sm">
            <span class="glyphicon glyphicon-user input-group-addon"></span>
            {{ form.username }}
        </div>
        <div class="input-group input-group-sm">
            <span class="glyphicon glyphicon-envelope input-group-addon"></span>
            {{ form.email }}
        </div>

        <div class="input-group input-group-sm">
            <span class="glyphicon glyphicon-lock input-group-addon"></span>
            {{ form.password1 }}
            {{ form.password2 }}
        </div>
        <div class="input-group input-group-sm">
        </div>
            <button type="submit" name="submit" class="btn btn-default btn-block">Sign in</button>
    </form>
{% endblock %}

Tiger_CTF/userpages/templates/userpages/userpages-base.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="well col-sm-4 col-sm-offset-4">
        {% block userpages-content %}
        {% endblock %}
    </div>
</div>
{% endblock %}