Tiger_CTF/Tiger_CTF/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from home import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from challenges import urls
from naming import urls as naming_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', auth_views.login, {'template_name':'userpages/login.html'}, name='login'),
    url(r'^logout$', auth_views.logout,{'template_name':'userpages/logout.html'}, name='logout'),
    url(r'^home$', views.home, name='home'),
    url(r'^user/', include('userpages.urls', namespace='userpages')),
    url(r'^challenges/', include(urls, namespace='challenges')),
    url(r'^naming/', include(naming_urls, namespace='naming')),
]
#Have django serve stati files and media in debug mode
#the apache server will take care of this when the server is
#deployed
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tiger_CTF/naming/urls.py
from django.conf.urls import include, url
from .views import naming, vote, score

urlpatterns = [
        url(r'^$', naming, name = 'naming'),
        url(r'^vote/([0-9]+)$', vote, name='vote'),
        url(r'^score/([0-9]+)$', vote, name='score'),
        ]

Tiger_CTF/naming/models.py
from django.db import models
from django.utils.html import format_html
from django.contrib.auth.models import User

class Namee(models.Model):
    RANK = [
        ('SSgt', 'Staff Sergeant'),
        ('TSgt', 'Technical Sergeant'),
        ('Capt', 'Captain'),
        ('Maj', 'Major'),
            ]
    rank = models.CharField(max_length=4, choices = RANK)
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    enabled = models.BooleanField(default=False)

    def __unicode__(self):
        return format_html('{} {}'.format(self.rank,
                                              self.last_name,
                                              )
                            )
class NickName(models.Model):
    namee = models.ForeignKey('Namee',
                       on_delete=models.CASCADE)
    nick = models.CharField(max_length=32)

    def __unicode__(self):
        return format_html('{} {} \"{}\" {}'.format(self.namee.rank, self.namee.first_name ,self.nick, self.namee.last_name))

class Vote(models.Model):
    nick_name = models.ForeignKey('NickName',
                      on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __unicode__(self):
        return format_html('{} - {}'.format(self.user, self.nick_name))
# Create your models here.

Tiger_CTF/naming/forms.py
from django import forms

class VoteForm(forms.Form):
    vote = forms.IntegerField(max_value=100)

Tiger_CTF/naming/views.py
from django.shortcuts import render
from django.http import Http404
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from .models import Namee, NickName, Vote
from django.contrib.auth.models import User
from .forms import VoteForm
from operator import itemgetter

def progress(nick_name):
    total_votes = float(Vote.objects.filter(nick_name=nick_name).count())
    perc_complete = 0
    if total_votes:
        total_users = float(User.objects.all().count()) - 2
        if total_users:
            perc_complete = int(total_votes/(total_users)*100)
            print 'Perc Complete:{}/{} {}'.format(total_users,total_votes,perc_complete)
    return perc_complete


@login_required
def naming(request):
    namees = Namee.objects.all()
    perc_complete = 0
    namees_disabled = Namee.objects.filter(enabled=False)
    nicks_count = NickName.objects.filter(namee=namees_disabled).annotate(vote_count=Count('vote'))
    set_nicks = [nicks_count.filter(
                namee=x,
                vote_count__gt=0
                ).order_by(
                    '-vote_count'
                    ).first() for x in namees_disabled]

    enabled_name = ''
    nick_votes= ''
    if namees.filter(enabled=True).exists():
        enabled_name = namees.filter(enabled=True)[0]
        nick_name = NickName.objects.filter(namee=enabled_name)
        nick_votes = [(x,Vote.objects.filter(nick_name__id=x.id).count()) for x in nick_name] 
        perc_complete = progress(nick_name)



    return render(request,
                  'naming/naming.html',
                  {'enabled_name':enabled_name, 
                   'namees':namees, 
                   'nick_votes':nick_votes, 
                   'set_nicks':set_nicks,
                   'perc_complete':perc_complete,
                   })

def sort_scores(nick_names):
            nick_names = [(x,Vote.objects.filter(nick_name__id=x.id).count()) for x in nick_names] 
            nick_names = sorted(nick_names, key=itemgetter(1))[::-1]
            nick_1 = nick_names[0]
            nick_2 = nick_names[1:4]
            nick_3 = nick_names[4:]
            return (nick_1,nick_2,nick_3)



@login_required
def vote(request, namee_id):
    namees = Namee.objects.all();
    namee = Namee.objects.get(id=namee_id)
    nick_names = NickName.objects.filter(namee=namee)
    perc_complete = progress(nick_names)
    if request.method == 'POST':
        form = VoteForm(request.POST)
        if form.is_valid():
            #vulnerable!!!!
            vote = form.cleaned_data['vote']
            nick = NickName.objects.get(id=vote)
            old_v = Vote.objects.filter(user=request.user, nick_name__namee=namee)
            old_v.delete()
            v = Vote(user=request.user,nick_name=nick)
            v.save()
            (nick_1,nick_2,nick_3) = sort_scores(nick_names)
            return render(request,'naming/votes.html',{ 
                                                       'namees':namees, 
                                                       'namee':namee,
                                                       'nick_1':nick_1,
                                                       'nick_2':nick_2,
                                                       'nick_3':nick_3,
                                                       'perc_complete':perc_complete,
                                                       })
        pass
    else:
        (nick_1,nick_2,nick_3) = sort_scores(nick_names)
        form = VoteForm()
        return render(request,'naming/votes.html',{
                                                    'namees':namees, 
                                                    'namee':namee,
                                                    'nick_1':nick_1,
                                                    'nick_2':nick_2,
                                                    'nick_3':nick_3,
                                                    'perc_complete':perc_complete,
                                                    })


@login_required
def score(request, namee_id):
    pass

# Create your views here.

Tiger_CTF/naming/templates/naming/base_naming.html
{% extends 'base-navbar.html' %}
{% block title %}
Naming
{% endblock %}
{% block page_title %}
<h1>VIPER Naming</h1>
{% endblock %}
{% block nav_contents %}
    {% for namee in namees %} 
    <li><a href={% url 'naming:vote' namee.id %}>{{ namee }}</a></li>
    {% endfor %}
{% endblock %}

Tiger_CTF/naming/templates/naming/naming.html
{% extends 'naming/base_naming.html' %}
{% block page_title %}
<h1> VIPER Naming </h1>
{% endblock %}
{% block title %}
Naming
{% endblock %}

{% block head %}
    <meta http-equiv="refresh" content="5">
{% endblock %}
{% block content %}
<div class="container-fluid">
{% if enabled_name %}
<h1> Currently Naming {{ enabled_name }} </h1>
{% include 'naming/progress_bar.html' %}
<div class="ct-chart"></div>
<script>
    var data = {
        labels: [{% for nick,votes in nick_votes %}'{{nick.nick}}',{% endfor %}],
        series: [
            [{% for nick, votes in nick_votes %}'{{votes}}',{%endfor%}]
                ]
    };
    var options = {
        onlyInteger: true,
    };
    new Chartist.Bar('.ct-chart', data, options);
    document.getElementById("ct-label").style.fontSize="xx-large";
</script>
{% else %}
<div class='well'>
    <h2> Welcome to the naming ceremony! </h2>
    <h3> Please connect your wireless device to the bellow SSID, and register with
        this web page to assist in tonights naming.</h3>
    <h3><strong>SSID: </strong>Tiger_Wireless</h3>
    <h3><strong>WPA-Passphrase: </strong>7iger_wireless_p@ss</h3>
    <h3><strong>WebPage IP: </strong>192.168.0.2</h3>
    <h3> No voting at the moment! </h3>
</div>
{% endif %}
{% if set_nicks %} 
<div class='well'>
    <h2> Named Pwnies: </h2>
    <ul class="list-group">
    {% for nick in set_nicks %}
        {% if nick %}
            <li class="list-group-item">
            <span class="label label-default label-pill pull-right">{{nick.vote_count}}</span>
            {{nick}}
            </li>
        {% endif %}
    {% endfor %}
    </ul>
</div>
{% endif %}
</div>
{% endblock %}

Tiger_CTF/naming/templates/naming/progress_bar.html
{% if perc_complete %}
<div class="progress">
    <div class="progress-bar" role="progressbar" aria-valuenow="{{perc_complete}}" aria-valuemin="0" aria-valuemax="100" style="width:{{perc_complete}}%">
        {{ perc_complete }}%
    </div>
</div>
{% endif %}

Tiger_CTF/naming/templates/naming/votes.html
{% extends 'naming/base_naming.html' %}
{% block title %}
    Naming Votes
{% endblock %}
{% block page_title %}
<h1>{{ namee }}</h1>
<div class='btn-group'>
    <button type='button' class='btn btn-success disabled'>1st</button>
    <button type='button' class='btn btn-warning disabled'>2nd-4th</button>
    <button type='button' class='btn btn-danger disabled'>> 4th</button>
</div>
{% endblock %}
{% block content %}
<div class="container-fluid ">
    {% if namee.enabled %}
    {% include 'naming/progress_bar.html' %}
    <form action="{% url 'naming:vote' namee.id %}" method="POST">
    {% csrf_token %}
        <div class='btn-group-vertical'>
            <button name='vote' type='submit' class='btn btn-success btn-block btn-lg' value="{{ nick_1.0.id }}">
                <span class="label label-info label-pill pull-right">{{nick_1.1}}</span>
                {{ nick_1.0.nick }} &nbsp 
            </button>
            {% for nick, score in nick_2 %}
            <button name='vote' type='submit' class='btn btn-warning btn-block btn-lg' value="{{ nick.id }}">
                <span class="label label-info label-pill pull-right">{{score}}</span>
                {{ nick.nick }} &nbsp 
            </button>
            {% endfor %}
            {% for nick, score in nick_3 %}
            <button name='vote' type='submit' class='btn btn-danger btn-block btn-lg' value="{{ nick.id }}">
                <span class="label label-info label-pill pull-right">{{score}}</span>
                {{ nick.nick }} &nbsp
            </button>
            {% endfor %}
        </div>
    </form>
    {% else %}
    <div class="well">
        {% if nick_1.1 %}
        <h1>{{ nick_1.0.namee }} will hence forth be known as <strong>{{ nick_1.0.nick }}</strong>!</h1>
        {% else %}
            <h1>Root has not yet allowed voting on this member!</h1>
        {% endif %}
    </div>
    {% endif %}
</div>
{% endblock %}