Tiger_CTF/Tiger_CTF/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from home import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from challenges import urls
from naming import urls as naming_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', auth_views.login, {'template_name':'userpages/login.html'}, name='login'),
    url(r'^logout$', auth_views.logout,{'template_name':'userpages/logout.html'}, name='logout'),
    url(r'^home$', views.home, name='home'),
    url(r'^user/', include('userpages.urls', namespace='userpages')),
    url(r'^challenges/', include(urls, namespace='challenges')),
    url(r'^naming/', include(naming_urls, namespace='naming')),
]
#Have django serve stati files and media in debug mode
#the apache server will take care of this when the server is
#deployed
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tiger_CTF/challenges/urls.py
from django.conf.urls import include, url
import views

urlpatterns = [
        url(r'^$', views.challenges, name='challenges'), 
        url(r'^(?P<challenge_number>[0-9]+)$', views.challenge, name='challenge'),
        ]

Tiger_CTF/naming/urls.py
from django.conf.urls import include, url
from .views import naming, vote, score

urlpatterns = [
        url(r'^$', naming, name = 'naming'),
        url(r'^vote/([0-9]+)$', vote, name='vote'),
        url(r'^score/([0-9]+)$', vote, name='score'),
        ]

Tiger_CTF/challenges/models.py
from django.db import models
from django.utils.html import format_html
from django.contrib.auth.models import User
# This is the database model for the CTF Challenges
class Challenge(models.Model):
    number = models.IntegerField(unique=True)
    description = models.TextField()
    hint = models.TextField()
    key = models.CharField(max_length=128)
    points = models.IntegerField()

    #This method adds challenge to the integer field of Challenge and 
    #allows you to order the models on the next line after the method
    def format_number(self):
        return format_html('Challenge {}',
                            self.number)
    number.admin_order_field = 'number'
    #required for displaying an printable item
    def __unicode__(self):
        return format_html('Challenge{}', self.number)


class ChallengeFile(models.Model):
    challenge = models.ForeignKey('Challenge',)
    fi = models.FileField()

    def __unicode__(self):
        return format_html('Challenge {} -- File: {}', self.challenge, self.fi) 

class UserScore(models.Model):
    user = models.ForeignKey(User)
    challenge = models.ForeignKey('Challenge')
    def __unicode__(self):
        return format_html('{} -- {}', self.user, self.challenge) 

Tiger_CTF/challenges/forms.py
from django import forms
from .models import Challenge, UserScore
from django.forms.util import ErrorList

class AnswerForm(forms.Form):
    answer = forms.CharField(label='Answer',max_length=100)

    def check_answer(self, chal, loged_user):
        ans = self.cleaned_data["answer"]
        if chal.key == ans:
            score = UserScore(user=loged_user, challenge=chal)
            score.save(force_insert=True)
            return True
        else:
            errors = self._errors.setdefault("answer",ErrorList())
            errors.append(u"That key was incorrect")
            return False

Tiger_CTF/challenges/views.py
from django.http import Http404
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Challenge,ChallengeFile, UserScore
from .forms import AnswerForm

def check_solved(user):
    challist = Challenge.objects.all()
    solved_list = [UserScore.objects.filter(challenge=x,user=user).exists() for x in challist]
    return zip(challist, solved_list)


@login_required
def challenges(request):
    challist = check_solved(request.user)
    return render(request,'challenges/challenges-base.html',{'challist':challist})

@login_required
def challenge(request, challenge_number):
    c_complete = ''
    challist = check_solved(request.user) 
    challenge = Challenge.objects.get(number=challenge_number)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            ans = form.cleaned_data
            if(form.check_answer(challenge, request.user)):
                c_complete = 'Congratulations, That is the correct key!'
            return render(request,'challenges/challenge.html',
                    {'challist':challist,
                     'challenge':challenge,
                     'form':form,
                     'c_complete':c_complete,
                     })
    else:
        form = AnswerForm()
        if (UserScore.objects.filter(challenge=challenge,user=request.user).exists()):
            c_complete = 'You have already completed this challenge!'

    return render(request,'challenges/challenge.html',
            {'challist':challist,
                'challenge':challenge,
                'form':form,
                'c_complete':c_complete,
                })


# Create your views here.

Tiger_CTF/challenges/templates/challenges/challenge.html
{% extends 'challenges/challenges-base.html' %}
{% block challenge_content %}
<div class="well">
<h2> Challenge: {{ challenge.number }} </h2>
<p><strong>Description:</strong> {{challenge.description}}</p>
<p><strong>Points:</strong> {{challenge.points}}</p>
{% if challenge.challengefiles_set.values %}
    <div class="well">
        <p><strong>Files:</strong></p>
    {% for value in challenge.challengefiles_set.values %}
    <a href="#">{{ value.fi }}</a>
    {% endfor %}
    </div>
{% endif %}
{% if c_complete %}
        <div class="alert alert-success">
            {{ c_complete }}
        </div>
{% else %}
{% if form.errors %}
        <div class="alert alert-danger">
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {% endfor %}
        </div>
{% endif %}
    <form action={% url 'challenges:challenge' challenge.number %} method="post">
        {% csrf_token %}
        <div class="input-group input-group-sm">
            <span class="glyphicon glyphicon-triangle-right input-group-addon"></span>
            {{ form.answer }}
            <input type="submit" value="Submit"/>
        </div>
    </form>
{% endif %}
</div>
{% endblock %}

Tiger_CTF/challenges/templates/challenges/challenges-base.html
{% extends 'base-navbar.html' %}
{% block content %}
<div class="container-fluid text-center">
    <div class="row content">
        <div class="col-sm-1 sidenav">
        {% for chal, solved in challist %}
            {% if solved %}
            <p><a href="{% url 'challenges:challenge' chal.number %}" class="btn btn-success" role="button">
            <span class="icon-stack">
                    <i class="glyphicon glyphicon-flag icon-stack-base"></i>
                    <i class="glyphicon glyphicon-flag"></i>
                </span> {{ chal.number }}
            </a><p>

            {% else %}
            <p><a href="{% url 'challenges:challenge' chal.number %}" class="btn btn-danger" role="button">
                <span class="icon-stack">
                    <i class="glyphicon glyphicon-flag icon-stack-base"></i>
                    <i class="glyphicon glyphicon-ban-circle"></i>
                </span> {{ chal.number }}
            </a><p>
            {% endif %}
        {% endfor %}
        </div>
        <div class="col-sm-9 text-left">
            {% block challenge_content %}
            <h1>Rules</h1>
            <p>These are the rules!</p>
            {% endblock %}
        </div>
        <div class="col-sm-2 sidenave">
            <div class="well">
                <p>Badges</p>
            </div>
            <div class="well">
                <p>Badges</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}